export const constants = {
    LOGIN_C:'LOGIN',
    ENTER_EMAIL_ID:'Enter Email Id',
    ENTER_PASSWORD:'Enter Password',
    NEW_PASSWORD:'New Password',
    LOGIN_BUTTON:'L O G I N',
    NEED_AN_ACCOUNT:"Need an account ?",
    SIGN_UP:' Sign Up',
    FORGOT_PASSWORD:'Forgot Password',
    DONE:'S U B M I T ',
    SIGN_UP_C: 'SIGN UP',
    LOGIN:'Login',
    ALREADY_AN_ACCOUNT:'Already an account ? ',
    FIRST_NAME:'First Name',
    LAST_NAME: "Last Name",
    CONFIRM_PASSWORD:'Confirm Password',
    VERIFICATION_CODE:'Verification code',
    OTP_TEXT:'Please type verification code sent',
    BOOKING_ROOM:'Available Meeting Room',
    OCCUPIED_ROOM:'Occupied Meeting Room',
    MEETING_ROOM:'Cabins',
    SELECT_A_LOCATION:'Where you want to a book meeting room?',
    SELECT_A_MEETING_ROOM:'Select a meeting room',
    TIMING:'Timing',
    SELECT_DATE_TIME:'Select a start Time and Buffer time',
    SLOT_TIME:'Select a buffer time',
    START_TIME:'Start Time',
    END_TIME:'End Time',
    BOOK_ROOM:'Book Room',
    SOME_ROOM_AVAILABLE:'Some time slot is available',
    ROOM_CAPACITY: 'room capacity ',
    EMPLOYEE_NAME:'Employee Name',
    EMPLOYEE_ID:'Employee Id',
    DURATION:'Duration',
    REASON:'Why you require?',
    SEND_INVITE:'Send Invites',
    LOCATION:'Location',
    CANCEL:'C A N C E L',
    NO_SLOT:'No buffer time slot is available in this time for this room, Please change your start time or change room.',
    BOOKING_LABEL:'you want to book an again meeting room then',
    CLICK_HERE:'Click here',
    RESET_PASSWORD:'Reset Password',
    EMAIL_ERROR_LABEL:'Please enter a valid email address which has provided by the Neosoft organization',
    NOT_FOUND_EMAIL:'We cannot find an account with that email address in our database',
    WARNING:'There was a problem',
    DELETE_MEETING_LABEL:'Are you sure want to cancel this meeting room ?',
    PASSWORD_MIS_MATCH:'your password and confirm password is not matching, please try it again',
    USER_CREDENTIAL_ERROR:'We cannot find an account with this credential in our database, please try it again.'
}