export const constants = {
    LOGIN_C:'LOGIN',
    ENTER_EMAIL_ID:'Enter Email Id',
    ENTER_PASSWORD:'Enter Password',
    LOGIN_BUTTON:'L O G I N',
    NEED_AN_ACCOUNT:"Need an accout ?",
    SIGN_UP:' Sign Up',
    FORGOT_PASSWORD:'Forgot Password',
    DONE:'D O N E',
    SIGN_UP_C: 'SIGN UP',
    LOGIN:'Login',
    ALREADY_AN_ACCOUT:'Already an account ? ',
    FIRST_NAME:'First Name',
    LAST_NAME: "Last Name",
    CONFIRMPASSWORD:'Confirm Password',
    VERIFICATION_CODE:'Verification code',
    OTP_TEXT:'Please type verification code sent',
    BOOKING_ROOM:'Available Meeting Room',
    OCCUPIED_ROOM:'Occupied Meeting Room',
    MEETING_ROOM:'Room',
    SELECT_A_LOCATION:'Select a location to book a meeting room',
    SELECT_A_MEETING_ROOM:'Select a meeting room',
    TIMING:'Timing',
    SELECT_DATE_TIME:'Select a start Time and Buffer time',
    SLOT_TIME:'Select a buffer time',
    START_TIME:'Start Time',
    END_TIME:'End Time',
    BOOK_ROOM:'Book Room',
    SOME_ROOM_AVAILABLE:'Some time slot is available',
    ROOM_CAPACITY: 'room capacity ',
    EMPLOYEE_NAME:'Employee Name',
    EMPLOYEE_ID:'Employee Id',
    DURATION:'Duration',
    REASON:'Why you require?',
    SEND_INVITE:'Send Invites',
    LOCATION:'Location',
    CANCEL:'C A N C E L'

}